let allFeatures=[],filtered=[],selected=null,selectedLayer=null,map,quarryLayer,districtLayer,drawnItems;
const $=id=>document.getElementById(id),val=id=>$(id).value,esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function initMap(){map=L.map("map").setView([10.45,76.3],8);const street=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map),sat=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{attribution:"Esri"});L.control.layers({"Street":street,"Satellite":sat}).addTo(map);drawnItems=new L.FeatureGroup().addTo(map);map.addControl(new L.Control.Draw({edit:{featureGroup:drawnItems},draw:{polygon:{allowIntersection:false,showArea:true},rectangle:false,circle:false,circlemarker:false,polyline:false,marker:false}}));map.on(L.Draw.Event.CREATED,e=>newQuarry(e.layer))}
async function load(){initMap();$("apiState").textContent=CONFIG.API_URL?"Apps Script configured":"Local mode";const[q,d]=await Promise.all([fetch(CONFIG.DATA_URL).then(r=>r.json()),fetch(CONFIG.DISTRICTS_URL).then(r=>r.json())]);allFeatures=q.features||[];districtLayer=L.geoJSON(d,{style:{color:"#4d6258",weight:1,fill:false}}).addTo(map);fillDistricts();await loadBackend();filters();fitAll()}
async function loadBackend(){if(!CONFIG.API_URL)return;try{const j=await fetch(CONFIG.API_URL+"?action=getAll").then(r=>r.json());const m=new Map((j.records||[]).map(x=>[String(x.quarry_id),x]));allFeatures.forEach(f=>{const p=f.properties||{},x=m.get(String(p.quarry_id));if(!x)return;Object.assign(p,{verification_status:x.status||p.verification_status,water_verified:x.water||p.water_verified,quarry_type_std:x.type||p.quarry_type_std,activity_status:x.activity||p.activity_status,verification_note:x.note||p.verification_note});if(x.geometry_json)try{f.geometry=JSON.parse(x.geometry_json)}catch(e){}})}catch(e){console.warn(e)}}
function fillDistricts(){const n=[...new Set(allFeatures.map(f=>f.properties?.district).filter(Boolean))].sort();$("district").innerHTML='<option value="">All districts</option>'+n.map(x=>'<option>'+esc(x)+'</option>').join("")}
function filters(){const d=val("district"),s=val("status"),w=val("waterFilter"),q=val("search").toLowerCase();filtered=allFeatures.filter(f=>{const p=f.properties||{};return(!d||p.district===d)&&(!s||p.verification_status===s)&&(!w||p.water_verified===w)&&(!q||[p.quarry_id,p.id,p.name,p.operator].join(" ").toLowerCase().includes(q))});renderList();renderMap();stats()}
function renderList(){$("count").textContent=filtered.length+" results";$("quarryList").innerHTML=filtered.map(f=>{const p=f.properties||{},s=p.verification_status||"Unverified";return '<div class="item '+(selected===p.quarry_id?"selected":"")+'" onclick="selectFeature(''+String(p.quarry_id).replace(/'/g,"\\'")+'')"><span class="dot '+s.toLowerCase()+'"></span><b>'+esc(p.quarry_id||"—")+'</b><br><small>'+esc(p.name||p.mineral||"OSM quarry")+' · '+esc(p.district||"")+'</small></div>'}).join("")}
function renderMap(){if(quarryLayer)quarryLayer.remove();quarryLayer=L.geoJSON({type:"FeatureCollection",features:filtered},{style:f=>{const s=f.properties?.verification_status||"Unverified";return{color:s==="Confirmed"?"#3b7d55":s==="Rejected"?"#b75b5b":"#4e7b64",weight:selected===f.properties?.quarry_id?4:1,fillOpacity:.18}},onEachFeature:(f,l)=>{l.on("click",()=>selectFeature(f.properties.quarry_id))}}).addTo(map);if(selected)highlight()}
function selectFeature(id){const f=allFeatures.find(x=>String(x.properties?.quarry_id)===String(id));if(!f)return;selected=id;const p=f.properties||{};$("empty").classList.add("hidden");$("details").classList.remove("hidden");$("qid").textContent=p.quarry_id||"—";$("qname").textContent=p.name||p.mineral||"OSM quarry";$("rank").textContent=p.rank!=null?"#"+p.rank:"";$("districtVal").textContent=p.district||"—";$("areaVal").textContent=p.area_ha!=null?p.area_ha+" ha":(p.area!=null?p.area:"—");$("sourceVal").textContent=p.source||p.source_system||"OSM";$("sourceMeta").innerHTML=Object.entries(p).filter(([k])=>!["geometry"].includes(k)).slice(0,18).map(([k,v])=>'<b>'+esc(k)+':</b> '+esc(v)).join(" · ");setChoice("isQuarry",p.verification_status||"Unverified");setChoice("hasWater",p.water_verified||"");$("extra").classList.toggle("hidden",p.verification_status!=="Rejected"&&p.verification_status!=="Unverified"&&p.verification_status!=="Uncertain"?false:true);$("activity").value=p.activity_status||"Unknown";$("waterType").value=p.water_type||"Unknown";$("type").value=p.quarry_type_std||"Unknown";$("confidence").value=p.verification_confidence||"High";$("note").value=p.verification_note||"";highlight();renderList()}
function setChoice(group,v){document.querySelectorAll("#"+group+" button").forEach(b=>b.classList.toggle("selected",b.dataset.v===v))}
function current(){return allFeatures.find(x=>String(x.properties?.quarry_id)===String(selected))}
function collect(){const f=current();if(!f)return null;const p=f.properties||{};p.verification_status=document.querySelector("#isQuarry .selected")?.dataset.v||"Unverified";p.water_verified=document.querySelector("#hasWater .selected")?.dataset.v||"Uncertain";p.activity_status=val("activity");p.water_type=val("waterType");p.quarry_type_std=val("type");p.verification_confidence=val("confidence");p.verification_note=val("note");p.verified_by=localStorage.getItem("workerName")||"";p.verified_at=new Date().toISOString();return f}
async function save(andNext=true){const f=collect();if(!f)return;localStorage.setItem("workerName",val("workerName"));localStorage.setItem("workerEmail",val("workerEmail"));if(CONFIG.API_URL){const r=await api("saveVerification",{feature:f,worker:{name:val("workerName"),email:val("workerEmail")}});if(!r.ok)return alert(r.message||"Save failed");$("apiState").textContent="Saved to Google Sheets"}else{localStorage.setItem("quarry_"+f.properties.quarry_id,JSON.stringify(f));$("apiState").textContent="Saved locally"};filters();if(andNext)move(1)}
async function api(action,payload){try{return await fetch(CONFIG.API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,...payload})}).then(r=>r.json())}catch(e){return{ok:false,message:e.message}}}
function move(dir){if(!filtered.length)return;let i=filtered.findIndex(f=>String(f.properties.quarry_id)===String(selected));selectFeature(filtered[(i<0?0:(i+dir+filtered.length)%filtered.length)].properties.quarry_id)}
function stats(){let p=allFeatures.map(f=>f.properties||{});$("total").textContent=p.length;$("pending").textContent=p.filter(x=>!x.verification_status||x.verification_status==="Unverified").length;$("confirmed").textContent=p.filter(x=>x.verification_status==="Confirmed").length;$("rejected").textContent=p.filter(x=>x.verification_status==="Rejected").length;$("waterCount").textContent=p.filter(x=>x.water_verified==="Yes").length}
function highlight(){if(!quarryLayer)return;quarryLayer.eachLayer(l=>{if(l.feature.properties.quarry_id===selected){l.setStyle({weight:5,fillOpacity:.35});l.bringToFront();map.fitBounds(l.getBounds().pad(.5))}})}
function fitAll(){if(quarryLayer){const b=quarryLayer.getBounds();if(b.isValid())map.fitBounds(b.pad(.1))}}
function newQuarry(layer){const id="NEW-"+Date.now();const f={type:"Feature",properties:{quarry_id:id,district:"",source:"Manual",verification_status:"Unverified",water_verified:"Uncertain",geometry_status:"New"},geometry:layer.toGeoJSON().geometry};allFeatures.push(f);drawnItems.addLayer(layer);selectFeature(id)}
function setup(){["district","status","waterFilter","search"].forEach(id=>$(id).addEventListener("input",filters));$("reset").onclick=()=>{["district","status","waterFilter","search"].forEach(id=>$(id).value="");filters()};$("startBtn").onclick=()=>{localStorage.setItem("workerName",val("workerName"));localStorage.setItem("workerEmail",val("workerEmail"))};document.querySelectorAll("#isQuarry button").forEach(b=>b.onclick=()=>{setChoice("isQuarry",b.dataset.v);$("extra").classList.toggle("hidden",b.dataset.v==="Rejected")});document.querySelectorAll("#hasWater button").forEach(b=>b.onclick=()=>setChoice("hasWater",b.dataset.v));$("save").onclick=()=>save(true);$("skip").onclick=()=>{setChoice("isQuarry","Uncertain");save(true)};$("next").onclick=()=>move(1);$("prev").onclick=()=>move(-1);$("nextPending").onclick=()=>{const f=allFeatures.find(x=>!x.properties.verification_status||x.properties.verification_status==="Unverified");if(f)selectFeature(f.properties.quarry_id)};$("drawNew").onclick=()=>new L.Draw.Polygon(map,{allowIntersection:false,showArea:true}).enable();$("editGeometry").onclick=()=>{const f=current();const l=quarryLayer?.getLayers().find(x=>x.feature.properties.quarry_id===selected);if(!f||!l)return;drawnItems.clearLayers();const e=L.geoJSON(l.toGeoJSON()).getLayers()[0];drawnItems.addLayer(e);e.on("edit",()=>{f.geometry=e.toGeoJSON().geometry;f.properties.geometry_status="Edited"});new L.EditToolbar.Edit(map,{featureGroup:drawnItems}).enable()}}
window.addEventListener("load",async()=>{const n=localStorage.getItem("workerName"),e=localStorage.getItem("workerEmail");if(n)$("workerName").value=n;if(e)$("workerEmail").value=e;setup();await load()});