let allFeatures=[],filtered=[],selected=null,selectedLayer=null,map,quarryLayer,districtLayer,drawnItems,currentWorker=null;
const $=id=>document.getElementById(id),val=id=>$(id).value,esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function showLogin(msg,ok=false){$("loginMsg").textContent=msg||"";$("loginMsg").className=ok?"ok":""}
function frameRequest(action,params={}){return new Promise((resolve,reject)=>{const id="req_"+Date.now()+"_"+Math.random().toString(36).slice(2),f=$("backendFrame");const timer=setTimeout(()=>{window.removeEventListener("message",handler);reject(new Error("Apps Script request timed out"))},15000);function handler(ev){if(!ev.data||ev.data._id!==id)return;clearTimeout(timer);window.removeEventListener("message",handler);resolve(ev.data.payload)}window.addEventListener("message",handler);const u=new URL(CONFIG.API_URL);u.searchParams.set("action",action);u.searchParams.set("_id",id);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));f.src=u.toString()})}
async function apiGet(action,params={}){return frameRequest(action==="authorize"?"authorizeFrame":"getAllFrame",params)}
async function login(){const name=$("loginName").value.trim();if(!name)return showLogin("Please enter your name.");if(!CONFIG.API_URL)return showLogin("The verification backend is not configured yet. Ask the administrator to add the Apps Script Web App URL.");$("loginBtn").disabled=true;showLogin("Checking access…");try{const j=await apiGet("authorize",{name});if(!j.authorized)return showLogin(j.message||"Access denied.");currentWorker={name};localStorage.setItem("workerName",name);$("loginGate").classList.add("hidden");$("app").classList.remove("hidden");$("workerDisplay").textContent=name;await load()}catch(e){showLogin("Could not connect to the verification server. "+e.message)}finally{$("loginBtn").disabled=false}}
function logout(){currentWorker=null;localStorage.removeItem("workerName");location.reload()}
function showError(e){console.error(e);$("mapStatus").textContent="Data loading error";$("apiState").textContent=e.message;alert("The quarry data could not be loaded. "+(e.message||e))}
function initMap(){map=L.map("map").setView([10.45,76.3],8);const street=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map),sat=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{attribution:"Esri"});L.control.layers({"Street":street,"Satellite":sat}).addTo(map);drawnItems=new L.FeatureGroup().addTo(map);map.addControl(new L.Control.Draw({edit:{featureGroup:drawnItems},draw:{polygon:{allowIntersection:false,showArea:true},rectangle:false,circle:false,circlemarker:false,polyline:false,marker:false}}));map.on(L.Draw.Event.CREATED,e=>newQuarry(e.layer))}
async function getJSON(url){const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error(url+" returned HTTP "+r.status);const t=await r.text();if(!t.trim())throw new Error(url+" is empty");try{return JSON.parse(t)}catch(e){throw new Error(url+" is not valid JSON")}}
async function load(){try{initMap();$("apiState").textContent="Loading quarry data…";const[q,d]=await Promise.all([getJSON(CONFIG.DATA_URL),getJSON(CONFIG.DISTRICTS_URL)]);if(!q||q.type!=="FeatureCollection")throw new Error("Quarry data is not a GeoJSON FeatureCollection");allFeatures=(q.features||[]).filter(f=>f&&f.geometry);if(!allFeatures.length)throw new Error("Quarry GeoJSON contains no features");districtLayer=L.geoJSON(d,{style:{color:"#4d6258",weight:1,fill:false}}).addTo(map);fillDistricts();filters();fitAll();$("apiState").textContent=allFeatures.length+" quarries loaded";$("mapStatus").classList.add("hidden")}catch(e){showError(e)}}
async function loadBackend(){const j=await apiGet("getAll");const m=new Map((j.records||[]).map(x=>[String(x.quarry_id),x]));allFeatures.forEach(f=>{const p=f.properties||{},x=m.get(String(p.quarry_id));if(!x)return;Object.assign(p,{verification_status:x.status||p.verification_status,verification_confidence:x.confidence||p.verification_confidence,water_verified:x.water||p.water_verified,water_type:x.water_type||p.water_type,quarry_type_std:x.type||p.quarry_type_std,activity_status:x.activity||p.activity_status,verification_note:x.note||p.verification_note});if(x.geometry_json)try{f.geometry=JSON.parse(x.geometry_json)}catch(e){}})}
function districtOf(p){return p.district||p.district_osm||""}
function fillDistricts(){const n=[...new Set(allFeatures.map(f=>districtOf(f.properties||{})).filter(Boolean))].sort();$("district").innerHTML='<option value="">All districts</option>'+n.map(x=>'<option>'+esc(x)+'</option>').join("")}
function filters(){const d=val("district"),s=val("status"),w=val("waterFilter"),q=val("search").toLowerCase();filtered=allFeatures.filter(f=>{const p=f.properties||{};return(!d||districtOf(p)===d)&&(!s||p.verification_status===s)&&(!w||p.water_verified===w)&&(!q||[p.quarry_id,p.osm_id,p.name,p.operator,p.mineral].join(" ").toLowerCase().includes(q))});renderList();renderMap();stats()}
function renderList(){$("count").textContent=filtered.length+" results";$("quarryList").innerHTML=filtered.map(f=>{const p=f.properties||{},s=p.verification_status||"Unverified";return '<div class="item '+(selected===p.quarry_id?"selected":"")+'" onclick="selectFeature(\''+String(p.quarry_id).replace(/'/g,"\\'")+"\')"><span class="dot "+s.toLowerCase()+""></span><b>"+esc(p.quarry_id||"—")+"</b><br><small>"+esc(p.name||p.mineral||"OSM quarry")+" · "+esc(districtOf(p))+"</small></div>"}).join("")}
function renderMap(){if(quarryLayer)quarryLayer.remove();quarryLayer=L.geoJSON({type:"FeatureCollection",features:filtered},{style:f=>{const s=f.properties?.verification_status||"Unverified";return{color:s==="Confirmed"?"#3b7d55":s==="Rejected"?"#b75b5b":"#4e7b64",weight:selected===f.properties?.quarry_id?4:1,fillOpacity:.18}},onEachFeature:(f,l)=>{l.bindTooltip(f.properties?.quarry_id||"Quarry");l.on("click",()=>selectFeature(f.properties.quarry_id))}}).addTo(map);if(selected)highlight()}
function selectFeature(id){const f=allFeatures.find(x=>String(x.properties?.quarry_id)===String(id));if(!f)return;selected=id;const p=f.properties||{};$("empty").classList.add("hidden");$("details").classList.remove("hidden");$("qid").textContent=p.quarry_id||"—";$("qname").textContent=p.name||p.mineral||"OSM quarry";$("rank").textContent=p.osm_rank!=null?"#"+p.osm_rank:"";$("districtVal").textContent=districtOf(p)||"—";$("areaVal").textContent=p.area_ha!=null?p.area_ha+" ha":(p.area_m2!=null?p.area_m2+" m²":"—");$("sourceVal").textContent=p.source||"OSM";$("sourceMeta").innerHTML=Object.entries(p).filter(([k])=>k!=="geometry").slice(0,18).map(([k,v])=>'<b>'+esc(k)+':</b> '+esc(v)).join(" · ");setChoice("isQuarry",p.verification_status||"Unverified");setChoice("hasWater",p.water_verified||"");$("extra").classList.toggle("hidden",!["Confirmed","Yes"].includes(p.verification_status));$("activity").value=p.activity_status||"Unknown";$("waterType").value=p.water_type||"Unknown";$("type").value=p.quarry_type_std||"Unknown";$("confidence").value=p.verification_confidence||"High";$("note").value=p.verification_note||"";highlight();renderList()}
function setChoice(group,v){document.querySelectorAll("#"+group+" button").forEach(b=>b.classList.toggle("selected",b.dataset.v===v))}
function current(){return allFeatures.find(x=>String(x.properties?.quarry_id)===String(selected))}
function collect(){const f=current();if(!f)return null;const p=f.properties||{};p.verification_status=document.querySelector("#isQuarry .selected")?.dataset.v||"Unverified";p.water_verified=document.querySelector("#hasWater .selected")?.dataset.v||"Uncertain";p.activity_status=val("activity");p.water_type=val("waterType");p.quarry_type_std=val("type");p.verification_confidence=val("confidence");p.verification_note=val("note");p.verified_by=currentWorker?.name||"";p.verified_at=new Date().toISOString();return f}
async function save(andNext=true){const f=collect();if(!f)return;const ok=await postForm({action:"saveVerification",feature:f,worker:currentWorker});if(!ok)return;filters();$("apiState").textContent="Verification submitted to Google Sheets";if(andNext)move(1)}
function postForm(payload){return new Promise(resolve=>{const iframe=document.getElementById("apiFrame"),form=document.getElementById("apiForm"),input=document.getElementById("apiPayload");input.value=JSON.stringify(payload);form.action=CONFIG.API_URL;form.target="apiFrame";iframe.onload=()=>{setTimeout(()=>resolve(true),250)};form.submit()})}
function move(dir){if(!filtered.length)return;let i=filtered.findIndex(f=>String(f.properties.quarry_id)===String(selected));selectFeature(filtered[(i<0?0:(i+dir+filtered.length)%filtered.length)].properties.quarry_id)}
function stats(){let p=allFeatures.map(f=>f.properties||{});$("total").textContent=p.length;$("pending").textContent=p.filter(x=>!x.verification_status||x.verification_status==="Unverified"||x.verification_status==="pending").length;$("confirmed").textContent=p.filter(x=>x.verification_status==="Confirmed"||x.verification_status==="Yes").length;$("rejected").textContent=p.filter(x=>x.verification_status==="Rejected"||x.verification_status==="No").length;$("waterCount").textContent=p.filter(x=>x.water_verified==="Yes").length}
function highlight(){if(!quarryLayer)return;quarryLayer.eachLayer(l=>{if(l.feature.properties.quarry_id===selected){l.setStyle({weight:5,fillOpacity:.35});l.bringToFront();map.fitBounds(l.getBounds().pad(.5))}})}
function fitAll(){if(quarryLayer){const b=quarryLayer.getBounds();if(b.isValid())map.fitBounds(b.pad(.1))}}
function newQuarry(layer){const id="NEW-"+Date.now();const f={type:"Feature",properties:{quarry_id:id,district:"",source:"Manual",verification_status:"Unverified",water_verified:"Uncertain",geometry_status:"New"},geometry:layer.toGeoJSON().geometry};allFeatures.push(f);drawnItems.addLayer(layer);selectFeature(id)}
function setup(){
["district","status","waterFilter","search"].forEach(id=>$(id).addEventListener("input",filters));
$("reset").onclick=()=>{["district","status","waterFilter","search"].forEach(id=>$(id).value="");filters()};
document.querySelectorAll("#isQuarry button").forEach(b=>b.onclick=()=>{setChoice("isQuarry",b.dataset.v);$("extra").classList.toggle("hidden",!["Confirmed","Yes"].includes(b.dataset.v))});
document.querySelectorAll("#hasWater button").forEach(b=>b.onclick=()=>setChoice("hasWater",b.dataset.v));
$("save").onclick=()=>save(true);
$("skip").onclick=()=>{setChoice("isQuarry","Uncertain");save(true)};
$("next").onclick=()=>move(1);
$("prev").onclick=()=>move(-1);
$("nextPending").onclick=()=>{const f=allFeatures.find(x=>!x.properties.verification_status||x.properties.verification_status==="Unverified"||x.properties.verification_status==="pending");if(f)selectFeature(f.properties.quarry_id)};
$("drawNew").onclick=()=>new L.Draw.Polygon(map,{allowIntersection:false,showArea:true}).enable();
$("editGeometry").onclick=()=>{const f=current();const l=quarryLayer?.getLayers().find(x=>x.feature.properties.quarry_id===selected);if(!f||!l)return;drawnItems.clearLayers();const e=L.geoJSON(l.toGeoJSON()).getLayers()[0];drawnItems.addLayer(e);e.on("edit",()=>{f.geometry=e.toGeoJSON().geometry;f.properties.geometry_status="Edited"});new L.EditToolbar.Edit(map,{featureGroup:drawnItems}).enable()}
}
window.addEventListener("load",async()=>{setup();let name=localStorage.getItem("workerName")||prompt("Enter your name for verification records:","");if(!name||!name.trim())name="Guest";name=name.trim();localStorage.setItem("workerName",name);currentWorker={name:name};$("workerDisplay").textContent=name;await load()});