const SHEET_ID=PropertiesService.getScriptProperties().getProperty("SHEET_ID")||"",REQUIRE_WORKER=true;
function ss_(){return SHEET_ID?SpreadsheetApp.openById(SHEET_ID):SpreadsheetApp.getActiveSpreadsheet()}
function sheet_(n,h){let s=ss_().getSheetByName(n);if(!s)s=ss_().insertSheet(n);if(s.getLastRow()===0)s.appendRow(h);return s}
function setup(){sheet_("verifications",["quarry_id","status","confidence","water","water_type","type","activity","note","worker_name","worker_email","timestamp","geometry_json"]);sheet_("workers",["email","name","active"]);return"Setup complete"}
function doGet(e){try{const a=e.parameter.action||"health",cb=e.parameter.callback||"";if(a==="authorize")return authorize_(e.parameter.email,e.parameter.name,cb);if(a==="getAll")return getAll_(cb);return out_({ok:true,service:"Kerala Quarry Verification Tool"},cb)}catch(x){return out_({ok:false,message:String(x)},e.parameter.callback||"")}}
function doPost(e){try{const b=JSON.parse((e.parameter&&e.parameter.payload)||((e.postData&&e.postData.contents)||"{}")),w=b.worker||{};if(REQUIRE_WORKER&&!valid_(w.email,w.name))return out_({ok:false,message:"Worker is not authorized"});if(b.action==="saveVerification")return save_(b.feature,w);return out_({ok:false,message:"Unknown action"})}catch(x){return out_({ok:false,message:String(x)})}}
function valid_(email,name){const s=ss_().getSheetByName("workers");if(!s||!email||!name)return false;const v=s.getDataRange().getValues(),em=String(email).trim().toLowerCase(),nm=String(name).trim().toLowerCase();return v.slice(1).some(r=>String(r[0]).trim().toLowerCase()===em&&String(r[1]).trim().toLowerCase()===nm&&String(r[2]).trim().toLowerCase()!=="false")}
function authorize_(email,name,cb){const ok=valid_(email,name);return out_({ok,authorized:ok,message:ok?"Access granted":"Name/email is not registered as an active worker"},cb)}
function save_(f,w){const p=f.properties||{},id=p.quarry_id;if(!id)return out_({ok:false,message:"Missing quarry_id"});const s=sheet_("verifications",["quarry_id","status","confidence","water","water_type","type","activity","note","worker_name","worker_email","timestamp","geometry_json"]),row=[id,p.verification_status||"",p.verification_confidence||"",p.water_verified||"",p.water_type||"",p.quarry_type_std||"",p.activity_status||"",p.verification_note||"",w.name||"",w.email||"",new Date(),JSON.stringify(f.geometry||null)];const v=s.getDataRange().getValues();let at=-1;for(let i=1;i<v.length;i++)if(String(v[i][0])===String(id)){at=i+1;break}if(at>0)s.getRange(at,1,1,row.length).setValues([row]);else s.appendRow(row);return out_({ok:true,quarry_id:id})}
function getAll_(cb){const s=ss_().getSheetByName("verifications");if(!s)return out_({ok:true,records:[]},cb);const v=s.getDataRange().getValues();return out_({ok:true,records:v.slice(1).map(r=>({quarry_id:r[0],status:r[1],confidence:r[2],water:r[3],water_type:r[4],type:r[5],activity:r[6],note:r[7],timestamp:r[10],geometry_json:r[11]}))},cb)}
function out_(o,cb){const t=JSON.stringify(o);return cb?ContentService.createTextOutput(cb+"("+t+")").setMimeType(ContentService.MimeType.JAVASCRIPT):ContentService.createTextOutput(t).setMimeType(ContentService.MimeType.JSON)}