const SHEET_ID=PropertiesService.getScriptProperties().getProperty("SHEET_ID")||"",REQUIRE_WORKER=false;
function ss_(){return SHEET_ID?SpreadsheetApp.openById(SHEET_ID):SpreadsheetApp.getActiveSpreadsheet()}
function sheet_(n,h){let s=ss_().getSheetByName(n);if(!s)s=ss_().insertSheet(n);if(s.getLastRow()===0)s.appendRow(h);return s}
function setup(){sheet_("verifications",["quarry_id","status","confidence","water","water_type","type","activity","note","worker_name","worker_email","timestamp","geometry_json"]);sheet_("workers",["email","name","active"]);return"Setup complete"}
function doGet(e){const a=e.parameter.action||"health";if(a==="getAll")return getAll_();return out_({ok:true,service:"Kerala Quarry Verification Tool"})}
function doPost(e){try{const b=JSON.parse(e.postData.contents||"{}"),w=b.worker||{};if(REQUIRE_WORKER&&!valid_(w.email))return out_({ok:false,message:"Worker not authorized"});if(b.action==="saveVerification")return save_(b.feature,w);return out_({ok:false,message:"Unknown action"})}catch(x){return out_({ok:false,message:String(x)})}}
function valid_(email){const s=ss_().getSheetByName("workers");if(!s)return false;const v=s.getDataRange().getValues();return v.slice(1).some(r=>String(r[0]).toLowerCase()===String(email).toLowerCase()&&String(r[2]).toLowerCase()!=="false")}
function save_(f,w){const p=f.properties||{},id=p.quarry_id;if(!id)return out_({ok:false,message:"Missing quarry_id"});const s=sheet_("verifications",["quarry_id","status","confidence","water","water_type","type","activity","note","worker_name","worker_email","timestamp","geometry_json"]),row=[id,p.verification_status||"",p.verification_confidence||"",p.water_verified||"",p.water_type||"",p.quarry_type_std||"",p.activity_status||"",p.verification_note||"",w.name||"",w.email||"",new Date(),JSON.stringify(f.geometry||null)];const v=s.getDataRange().getValues();let at=-1;for(let i=1;i<v.length;i++)if(String(v[i][0])===String(id)){at=i+1;break}if(at>0)s.getRange(at,1,1,row.length).setValues([row]);else s.appendRow(row);return out_({ok:true,quarry_id:id})}
function getAll_(){const s=ss_().getSheetByName("verifications");if(!s)return out_({ok:true,records:[]});const v=s.getDataRange().getValues();return out_({ok:true,records:v.slice(1).map(r=>({quarry_id:r[0],status:r[1],confidence:r[2],water:r[3],water_type:r[4],type:r[5],activity:r[6],note:r[7],worker:r[8],timestamp:r[10],geometry_json:r[11]}))})}
function out_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}